from modules.variable_analysis import run_multiple_linear_regression, run_multiple_pls, run_lasso_regression, \
    create_transformed_features
from scripts.womac.womac_relationships import moaks_shared_womac_drop_df

moaks_shared_womac_drop_left_df = moaks_shared_womac_drop_df[moaks_shared_womac_drop_df['SIDE']==1]
moaks_shared_womac_drop_right_df = moaks_shared_womac_drop_df[moaks_shared_womac_drop_df['SIDE']==2]

v00_womac_drop_left_mbm_columns = moaks_shared_womac_drop_left_df[[column for column in moaks_shared_womac_drop_left_df.columns if 'V00MBM' in column]]
v01_womac_drop_left_mbm_columns = moaks_shared_womac_drop_left_df[[column for column in moaks_shared_womac_drop_left_df.columns if 'V01MBM' in column]]

v00_womac_drop_right_mbm_columns = moaks_shared_womac_drop_right_df[[column for column in moaks_shared_womac_drop_right_df.columns if 'V00MBM' in column]]
v01_womac_drop_right_mbm_columns = moaks_shared_womac_drop_right_df[[column for column in moaks_shared_womac_drop_right_df.columns if 'V01MBM' in column]]

v01_womac_drop_left_womac_columns = moaks_shared_womac_drop_left_df[['V01WOMADLL','V01WOMSTFL']]
v03_womac_drop_left_womac_columns = moaks_shared_womac_drop_left_df[['V03WOMADLL','V03WOMSTFL']]
womac_drop_left_womac_change_columns = moaks_shared_womac_drop_left_df[['ΔWOMADLL','ΔWOMSTFL']]

v01_womac_drop_left_pc_columns = moaks_shared_womac_drop_left_df[['V01LPC1','V01LPC2']]
v03_womac_drop_left_pc_columns = moaks_shared_womac_drop_left_df[['V03LPC1','V03LPC2']]
womac_drop_left_pc_change_columns = moaks_shared_womac_drop_left_df[['ΔLPC1','ΔLPC2']]

v01_womac_drop_right_womac_columns = moaks_shared_womac_drop_right_df[['V01WOMADLR','V01WOMSTFR']]
v03_womac_drop_right_womac_columns = moaks_shared_womac_drop_right_df[['V03WOMADLR','V03WOMSTFR']]
womac_drop_right_womac_change_columns = moaks_shared_womac_drop_right_df[['ΔWOMADLR','ΔWOMSTFR']]

v01_womac_drop_right_pc_columns = moaks_shared_womac_drop_right_df[['V01RPC1','V01RPC2']]
v03_womac_drop_right_pc_columns = moaks_shared_womac_drop_right_df[['V03RPC1','V03RPC2']]
womac_drop_right_pc_change_columns = moaks_shared_womac_drop_right_df[['ΔRPC1','ΔRPC2']]

# ========== WOMAC matrix analysis through multivariate linear regression (LR) of MBM variables ========= #

_, v00_v01_womac_left_drop_results, v00_v01_womac_left_p_matrix = run_multiple_linear_regression(v00_womac_drop_left_mbm_columns, v01_womac_drop_left_womac_columns)
_, v00_v03_womac_left_drop_results, v00_v03_womac_left_p_matrix = run_multiple_linear_regression(v00_womac_drop_left_mbm_columns, v03_womac_drop_left_womac_columns)
_, v01_v03_womac_left_drop_results, v01_v03_womac_left_p_matrix = run_multiple_linear_regression(v01_womac_drop_left_mbm_columns, v03_womac_drop_left_womac_columns)
_, v00_womac_left_drop_change_results, v00_womac_left_change_p_matrix = run_multiple_linear_regression(v00_womac_drop_left_mbm_columns, womac_drop_left_womac_change_columns)
_, v01_womac_left_drop_change_results, v01_womac_left_change_p_matrix = run_multiple_linear_regression(v01_womac_drop_left_mbm_columns, womac_drop_left_womac_change_columns)

_, v00_v01_womac_right_drop_results, v00_v01_womac_right_p_matrix = run_multiple_linear_regression(v00_womac_drop_right_mbm_columns, v01_womac_drop_right_womac_columns)
_, v00_v03_womac_right_drop_results, v00_v03_womac_right_p_matrix = run_multiple_linear_regression(v00_womac_drop_right_mbm_columns, v03_womac_drop_right_womac_columns)
_, v01_v03_womac_right_drop_results, v01_v03_womac_right_p_matrix = run_multiple_linear_regression(v01_womac_drop_right_mbm_columns, v03_womac_drop_right_womac_columns)
_, v00_womac_right_drop_change_results, v00_womac_right_change_p_matrix = run_multiple_linear_regression(v00_womac_drop_right_mbm_columns, womac_drop_right_womac_change_columns)
_, v01_womac_right_drop_change_results, v01_womac_right_change_p_matrix = run_multiple_linear_regression(v01_womac_drop_right_mbm_columns, womac_drop_right_womac_change_columns)

# ========== WOMAC PC1, PC2 analysis through multivariate linear regression (LR) of MBM variables ========= #

_, v00_v01_womac_left_drop_pc_results, v00_v01_womac_left_pc_p_matrix = run_multiple_linear_regression(v00_womac_drop_left_mbm_columns, v01_womac_drop_left_pc_columns)
_, v00_v03_womac_left_drop_pc_results, v00_v03_womac_left_pc_p_matrix = run_multiple_linear_regression(v00_womac_drop_left_mbm_columns, v03_womac_drop_left_pc_columns)
_, v01_v03_womac_left_drop_pc_results, v01_v03_womac_left_pc_p_matrix = run_multiple_linear_regression(v01_womac_drop_left_mbm_columns, v03_womac_drop_left_pc_columns)
_, v00_womac_left_drop_change_pc_results, v00_womac_left_change_pc_p_matrix = run_multiple_linear_regression(v00_womac_drop_left_mbm_columns, womac_drop_left_pc_change_columns)
_, v01_womac_left_drop_change_pc_results, v01_womac_left_change_pc_p_matrix = run_multiple_linear_regression(v01_womac_drop_left_mbm_columns, womac_drop_left_pc_change_columns)

_, v00_v01_womac_right_drop_pc_results, v00_v01_womac_right_pc_p_matrix = run_multiple_linear_regression(v00_womac_drop_right_mbm_columns, v01_womac_drop_right_pc_columns)
_, v00_v03_womac_right_drop_pc_results, v00_v03_womac_right_pc_p_matrix = run_multiple_linear_regression(v00_womac_drop_right_mbm_columns, v03_womac_drop_right_pc_columns)
_, v01_v03_womac_right_drop_pc_results, v01_v03_womac_right_pc_p_matrix = run_multiple_linear_regression(v01_womac_drop_right_mbm_columns, v03_womac_drop_right_pc_columns)
_, v00_womac_right_drop_change_pc_results, v00_womac_right_change_pc_p_matrix = run_multiple_linear_regression(v00_womac_drop_right_mbm_columns, womac_drop_right_pc_change_columns)
_, v01_womac_right_drop_change_pc_results, v01_womac_right_change_pc_p_matrix = run_multiple_linear_regression(v01_womac_drop_right_mbm_columns, womac_drop_right_pc_change_columns)

# ========== MBM matrix reduction and WOMAC matrix analysis through partial least squares (PLS) ========= #

_, v00_v01_womac_left_drop_pls_results, v00_v01_womac_left_pls_coef_matrix, v00_v01_womac_left_pls_constructs = run_multiple_pls(v00_womac_drop_left_mbm_columns, v01_womac_drop_left_womac_columns)
_, v00_v03_womac_left_drop_pls_results, v00_v03_womac_left_pls_coef_matrix, v00_v03_womac_left_pls_constructs = run_multiple_pls(v00_womac_drop_left_mbm_columns, v03_womac_drop_left_womac_columns)
_, v01_v03_womac_left_drop_pls_results, v01_v03_womac_left_pls_coef_matrix, v01_v03_womac_left_pls_constructs = run_multiple_pls(v01_womac_drop_left_mbm_columns, v03_womac_drop_left_womac_columns)
_, v00_womac_left_drop_change_pls_results, v00_womac_left_change_pls_coef_matrix, v00_womac_left_change_pls_constructs = run_multiple_pls(v00_womac_drop_left_mbm_columns, womac_drop_left_womac_change_columns)
_, v01_womac_left_drop_change_pls_results, v01_womac_left_change_pls_coef_matrix, v01_womac_left_change_pls_constructs = run_multiple_pls(v01_womac_drop_left_mbm_columns, womac_drop_left_womac_change_columns)

_, v00_v01_womac_right_drop_pls_results, v00_v01_womac_right_pls_coef_matrix, v00_v01_womac_right_pls_constructs = run_multiple_pls(v00_womac_drop_right_mbm_columns, v01_womac_drop_right_womac_columns)
_, v00_v03_womac_right_drop_pls_results, v00_v03_womac_right_pls_coef_matrix, v00_v03_womac_right_pls_constructs = run_multiple_pls(v00_womac_drop_right_mbm_columns, v03_womac_drop_right_womac_columns)
_, v01_v03_womac_right_drop_pls_results, v01_v03_womac_right_pls_coef_matrix, v01_v03_womac_right_pls_constructs = run_multiple_pls(v01_womac_drop_right_mbm_columns, v03_womac_drop_right_womac_columns)
_, v00_womac_right_drop_change_pls_results, v00_womac_right_change_pls_coef_matrix, v00_womac_right_change_pls_constructs = run_multiple_pls(v00_womac_drop_right_mbm_columns, womac_drop_right_womac_change_columns)
_, v01_womac_right_drop_change_pls_results, v01_womac_right_change_pls_coef_matrix, v01_womac_right_change_pls_constructs = run_multiple_pls(v01_womac_drop_right_mbm_columns, womac_drop_right_womac_change_columns)

# ========== MBM matrix reduction and WOMAC matrix analysis through L1 regularisation ========== #

_, v00_v01_womac_left_drop_lasso_results, v00_v01_womac_left_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_left_mbm_columns, v01_womac_drop_left_womac_columns)
_, v00_v03_womac_left_drop_lasso_results, v00_v03_womac_left_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_left_mbm_columns, v03_womac_drop_left_womac_columns)
_, v01_v03_womac_left_drop_lasso_results, v01_v03_womac_left_lasso_coef_matrix = run_lasso_regression(v01_womac_drop_left_mbm_columns, v03_womac_drop_left_womac_columns)
_, v00_womac_left_drop_change_lasso_results, v00_womac_left_change_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_left_mbm_columns, womac_drop_left_womac_change_columns)
_, v01_womac_left_drop_change_lasso_results, v01_womac_left_change_lasso_coef_matrix = run_lasso_regression(v01_womac_drop_left_mbm_columns, womac_drop_left_womac_change_columns)

_, v00_v01_womac_right_drop_lasso_results, v00_v01_womac_right_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_right_mbm_columns, v01_womac_drop_right_womac_columns)
_, v00_v03_womac_right_drop_lasso_results, v00_v03_womac_right_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_right_mbm_columns, v03_womac_drop_right_womac_columns)
_, v01_v03_womac_right_drop_lasso_results, v01_v03_womac_right_lasso_coef_matrix = run_lasso_regression(v01_womac_drop_right_mbm_columns, v03_womac_drop_right_womac_columns)
_, v00_womac_right_drop_change_lasso_results, v00_womac_right_change_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_right_mbm_columns, womac_drop_right_womac_change_columns)
_, v01_womac_right_drop_change_lasso_results, v01_womac_right_change_lasso_coef_matrix = run_lasso_regression(v01_womac_drop_right_mbm_columns, womac_drop_right_womac_change_columns)

# ========== Transformed MBM matrix reduction and WOMAC matrix analysis through L1 regularisation ========== #

v00_nonzero_features = v00_v01_womac_left_lasso_coef_matrix[
    (v00_v01_womac_left_lasso_coef_matrix['Coefficient'] != 0) &
    (v00_v01_womac_left_lasso_coef_matrix['Feature'] != 'Intercept')
]['Feature'].drop_duplicates().tolist()

v00_womac_drop_left_mbm_columns_filtered = v00_womac_drop_left_mbm_columns[v00_nonzero_features]
v00_womac_drop_left_mbm_columns_transformed = create_transformed_features(v00_womac_drop_left_mbm_columns_filtered)

v01_nonzero_features = v01_v03_womac_left_lasso_coef_matrix[
    (v01_v03_womac_left_lasso_coef_matrix['Coefficient'] != 0) &
    (v01_v03_womac_left_lasso_coef_matrix['Feature'] != 'Intercept')
]['Feature'].drop_duplicates().tolist()

v01_womac_drop_left_mbm_columns_filtered = v01_womac_drop_left_mbm_columns[v01_nonzero_features]
v01_womac_drop_left_mbm_columns_transformed = create_transformed_features(v01_womac_drop_left_mbm_columns_filtered)

_, v00_v01_womac_left_drop_transformed_lasso_results, v00_v01_womac_left_transformed_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_left_mbm_columns_transformed, v01_womac_drop_left_womac_columns)
_, v00_v03_womac_left_drop_transformed_lasso_results, v00_v03_womac_left_transformed_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_left_mbm_columns_transformed, v03_womac_drop_left_womac_columns)
_, v01_v03_womac_left_drop_transformed_lasso_results, v01_v03_womac_left_transformed_lasso_coef_matrix = run_lasso_regression(v01_womac_drop_left_mbm_columns_transformed, v03_womac_drop_left_womac_columns)
_, v00_womac_left_drop_change_transformed_lasso_results, v00_womac_left_change_transformed_lasso_coef_matrix = run_lasso_regression(v00_womac_drop_left_mbm_columns_transformed, womac_drop_left_womac_change_columns)
_, v01_womac_left_drop_change_transformed_lasso_results, v01_womac_left_change_transformed_lasso_coef_matrix = run_lasso_regression(v01_womac_drop_left_mbm_columns_transformed, womac_drop_left_womac_change_columns)
