from missing_imputation import moaks_shared_kl_drop_df, moaks_shared_kl_median_df
from modules.variable_analysis import run_linear_regression
from scripts.mbm.kl_oriented.mbm_var_relationships_kl import v00_moaks_shared_kl_drop_mbm_df, v01_moaks_shared_kl_drop_mbm_df, \
    v00_moaks_shared_kl_median_mbm_df, v01_moaks_shared_kl_median_mbm_df, v00_moaks_shared_kl_drop_mbm_reduced_df, \
    v01_moaks_shared_kl_drop_mbm_reduced_df

v01_kl_drop = moaks_shared_kl_drop_df['V01XRKL']
v03_kl_drop = moaks_shared_kl_drop_df['V03XRKL']
Δkl_drop = v03_kl_drop - v01_kl_drop

v01_kl_median = moaks_shared_kl_median_df['V01XRKL']
v03_kl_median = moaks_shared_kl_median_df['V03XRKL']
Δkl_median = v03_kl_median - v01_kl_median

_, v00_v01_kl_drop_results, v00_v01_kl_drop_coef_df = run_linear_regression(v00_moaks_shared_kl_drop_mbm_df,v01_kl_drop)
_, v00_v03_kl_drop_results, v00_v03_kl_drop_coef_df = run_linear_regression(v00_moaks_shared_kl_drop_mbm_df,v03_kl_drop)
_, v01_v03_kl_drop_results, v01_v03_kl_drop_coef_df = run_linear_regression(v01_moaks_shared_kl_drop_mbm_df,v03_kl_drop)
_, v00_kl_drop_change_results, v00_kl_drop_change_coef_df = run_linear_regression(v00_moaks_shared_kl_drop_mbm_df,Δkl_drop)
_, v01_kl_drop_change_results, v01_kl_drop_change_coef_df = run_linear_regression(v01_moaks_shared_kl_drop_mbm_df,Δkl_drop)

_, v00_v01_kl_drop_reduced_results, v00_v01_kl_drop_reduced_coef_df = run_linear_regression(v00_moaks_shared_kl_drop_mbm_reduced_df,v01_kl_drop)
_, v00_v03_kl_drop_reduced_results, v00_v03_kl_drop_reduced_coef_df = run_linear_regression(v00_moaks_shared_kl_drop_mbm_reduced_df,v03_kl_drop)
_, v01_v03_kl_drop_reduced_results, v01_v03_kl_drop_reduced_coef_df = run_linear_regression(v01_moaks_shared_kl_drop_mbm_reduced_df,v03_kl_drop)
_, v00_kl_drop_reduced_change_results, v00_kl_drop_reduced_change_coef_df = run_linear_regression(v00_moaks_shared_kl_drop_mbm_reduced_df,Δkl_drop)
_, v01_kl_drop_reduced_change_results, v01_kl_drop_reduced_change_coef_df = run_linear_regression(v01_moaks_shared_kl_drop_mbm_reduced_df,Δkl_drop)

_, v00_v01_kl_median_results, v00_v01_kl_median_coef_df = run_linear_regression(v00_moaks_shared_kl_median_mbm_df,v01_kl_median)
_, v00_v03_kl_median_results, v00_v03_kl_median_coef_df = run_linear_regression(v00_moaks_shared_kl_median_mbm_df,v03_kl_median)
_, v01_v03_kl_median_results, v01_v03_kl_median_coef_df = run_linear_regression(v01_moaks_shared_kl_median_mbm_df,v03_kl_median)



